/** @format */

import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import { Providers } from "./providers";
import Header from "@/components/header";

const geistSans = localFont({
  src: "../../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const latinModernMono = localFont({
  src: "../../public/fonts/lmmono10-regular.otf",
  variable: "--font-lmmono",
});
const kolkerBrush = localFont({
  src: "../../public/fonts/KolkerBrush-Regular.ttf",
  variable: "--font-kolker-brush",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`${geistSans.variable} ${geistMono.variable} ${kolkerBrush.variable} ${latinModernMono.variable} font-lmmono bg-primary-gray min-h-lvh`}
      ><Providers> <section><nav>
        <Header/>
      </nav>
      {children}
      </section>
      </Providers>
      </body>
    </html>
  );
}