/** @format */

import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import { Providers } from "./providers";
import Header from "@/components/header";

const latinModernMono = localFont({
  src: "../../public/fonts/lmmono10-regular.otf",
  variable: "--font-lmmono",
});
const kolkerBrush = localFont({
  src: "../../public/fonts/KolkerBrush-Regular.ttf",
  variable: "--font-kolker-brush",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kolkerBrush.variable} ${latinModernMono.variable} font-lmmono bg-[radial-gradient(169.40%_89.55%_at_94.76%_6.29%,rgba(0,0,0,0.80)_0%,rgba(255,255,255,0.00)_100%)] flex flex-col min-h-lvh`}
      >
        <Providers>
          {" "}
          <section>
            <nav>
              <Header />
            </nav>
            {children}
          </section>
        </Providers>
      </body>
    </html>
  );
}
